[build] Make mksnapshot build with clang explicitly
It appears that mksnapshot recipe append do not set up 'is_clang'
variable for GN_ARGS as true. It worked because of inaccurate logic
insertion in //build/config/BUILDCONFIG.gn file, made in
http://text.lge.com/neva/gerrit/#/c/3131 and
http://text.lge.com/neva/gerrit/#/c/2215/ Neva's CL's. After restoring
original upstream state of BUILDCONFIG.gn build failed with the error:
| build step: x64_cxx "x64/obj/third_party/abseil-cpp/absl/debugging/leak_check/leak_check.o"
| stderr:
| /home/ats/jenkins-slave/workspace/NEVA/webosose-github-builder/repos.d/mercury.lge.net/neva/chromium/src/third_party/libc++/src/include/__configuration/compiler.h:45:8: warning: #warning "Libc++ only supports GCC 15 and later" [-Wcpp]
|    45 | #      warning "Libc++ only supports GCC 15 and later"
|       |        ^~~~~~~
| In file included from /home/ats/jenkins-slave/workspace/NEVA/webosose-github-builder/repos.d/mercury.lge.net/neva/chromium/src/third_party/libc++/src/include/__config:17:
| /home/ats/jenkins-slave/workspace/NEVA/webosose-github-builder/repos.d/mercury.lge.net/neva/chromium/src/third_party/libc++/src/include/__configuration/experimental.h:18:18: error: missing binary operator before token "("
|    18 | #if __has_feature(experimental_library)
|       |                  ^
| /home/ats/jenkins-slave/workspace/NEVA/webosose-github-builder/repos.d/mercury.lge.net/neva/chromium/src/third_party/libc++/src/include/__config:181:22: error: missing binary operator before token "("
|   181 | #  if __has_extension(blocks) && defined(__APPLE__)
|       |                      ^
| /home/ats/jenkins-slave/workspace/NEVA/webosose-github-builder/repos.d/mercury.lge.net/neva/chromium/src/third_party/libc++/src/include/__config:723:20: error: missing binary operator before token "("
|   723 | #  if __has_feature(cxx_atomic) || __has_extension(c_atomic) || __has_keyword(_Atomic)
|       |                    ^
| /home/ats/jenkins-slave/workspace/NEVA/webosose-github-builder/repos.d/mercury.lge.net/neva/chromium/src/third_party/libc++/src/include/__config:1052:20: error: missing binary operator before token "("
|  1052 | #  if __has_feature(nullability)

It means that without breaking upstream logic mksnapshot is built with
GCC. That isn't appropriate for Neva. To fix this 'is_clang=true'
explicitly added to GN_ARGS.

Test Scenario:
1. Build Neva targets for webOS/OSE.
2. BVT test is passed successfully.

Issue: NEVA-11181, NEVA-10687